# Generated by Django 2.2.10 on 2021-03-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='', max_length=20)),
                ('course_name', models.CharField(max_length=30)),
                ('course_type', models.CharField(max_length=30)),
                ('course_duration', models.CharField(max_length=30)),
                ('course_instructor', models.CharField(max_length=30)),
                ('course_category', models.CharField(max_length=30)),
                ('course_url', models.URLField()),
                ('candiate_id', models.CharField(max_length=30)),
                ('candidate_name', models.CharField(max_length=30)),
                ('mentor_id', models.CharField(max_length=30)),
                ('mentor_name', models.CharField(max_length=30)),
            ],
        ),
    ]
