# Generated by Django 2.2.10 on 2021-03-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('course_type', models.CharField(max_length=30)),
                ('course_duration', models.CharField(max_length=30)),
                ('course_instructor', models.CharField(max_length=30)),
                ('course_category', models.CharField(max_length=30)),
                ('course_url', models.URLField()),
            ],
        ),
    ]
