# Generated by Django 2.2.10 on 2021-03-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoresheet', '0003_auto_20210316_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='course_category',
            field=models.CharField(default='', max_length=30),
        ),
    ]
