# Generated by Django 2.2.10 on 2021-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210320_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$ed9UGUeVRmKG$NdcJ2rrmNDq9fDDQwhn0gP0RoBmov06oZhTjAQELmS8=', max_length=128, verbose_name='password'),
        ),
    ]
