# Generated by Django 2.2.10 on 2021-03-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210320_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$4CywCwRZFBja$QwMT6ULv0la8Hcu8k7VJ1iL2/iyvb/X0yMOk/2HVe3U=', max_length=128, verbose_name='password'),
        ),
    ]
