# Generated by Django 2.2.10 on 2021-03-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210320_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='cpart', max_length=128, verbose_name='password'),
        ),
    ]
