# Generated by Django 2.2.10 on 2021-03-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='cpart', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
