# Generated by Django 2.2.10 on 2021-03-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestedcourse', '0002_auto_20210318_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedcourse',
            name='course_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='suggestedcourse',
            name='course_instructor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suggestedcourse',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='suggestedcourse',
            name='course_type',
            field=models.CharField(max_length=50),
        ),
    ]
