# Generated by Django 2.2.10 on 2021-03-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestedcourse', '0003_auto_20210318_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedcourse',
            old_name='course_category',
            new_name='suggested_course_category',
        ),
        migrations.RenameField(
            model_name='suggestedcourse',
            old_name='course_duration',
            new_name='suggested_course_duration',
        ),
        migrations.RenameField(
            model_name='suggestedcourse',
            old_name='course_url',
            new_name='suggested_course_url',
        ),
        migrations.RemoveField(
            model_name='suggestedcourse',
            name='course_instructor',
        ),
        migrations.RemoveField(
            model_name='suggestedcourse',
            name='mentee_id',
        ),
        migrations.RemoveField(
            model_name='suggestedcourse',
            name='mentee_name',
        ),
        migrations.RemoveField(
            model_name='suggestedcourse',
            name='mentor_id',
        ),
        migrations.RemoveField(
            model_name='suggestedcourse',
            name='mentor_name',
        ),
        migrations.AddField(
            model_name='suggestedcourse',
            name='suggested_course_instructor',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestedcourse',
            name='suggested_course_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestedcourse',
            name='suggested_mentee_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestedcourse',
            name='suggested_mentee_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestedcourse',
            name='suggested_mentor_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestedcourse',
            name='suggested_mentor_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestedcourse',
            name='course_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='suggestedcourse',
            name='course_type',
            field=models.CharField(max_length=150),
        ),
    ]
