# Generated by Django 2.2.10 on 2021-03-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestedcourse', '0004_auto_20210319_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedcourse',
            old_name='course_type',
            new_name='course_category',
        ),
    ]
