# Generated by Django 2.2.10 on 2021-03-19 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestedcourse', '0006_auto_20210319_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedcourse',
            name='assigned_on',
            field=models.DateField(default=datetime.date(2021, 3, 19)),
        ),
    ]
