# Generated by Django 2.2.10 on 2021-03-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestedcourse', '0008_suggestedcourse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedcourse',
            name='suggested_course_id',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
