# Generated by Django 2.2.10 on 2021-03-20 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestedcourse', '0009_suggestedcourse_suggested_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedcourse',
            name='assigned_on',
            field=models.DateField(default=datetime.date(2021, 3, 20)),
        ),
    ]
